CONTANTS_COMMON_DIR :=

CONTANTS_COMMON_DIR += $(CURDIR)/Contants/ChapterTitles
CONTANTS_COMMON_DIR += $(CURDIR)/Contants/Sounds
CONTANTS_COMMON_DIR += $(CURDIR)/Contants/Sprite
CONTANTS_COMMON_DIR += $(CURDIR)/Contants/TileSets
CONTANTS_COMMON_DIR += $(CURDIR)/Contants/TitleScreen

HACK_DIRS += $(CONTANTS_COMMON_DIR)
